# Generated by Django 4.2.14 on 2024-08-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=355)),
                ('email', models.EmailField(max_length=54)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
