# Generated by Django 4.2.14 on 2024-08-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '🌟✩✩✩✩'), (2, '🌟🌟✩✩✩'), (3, '🌟🌟🌟✩✩'), (4, '🌟🌟🌟🌟✩'), (5, '🌟🌟🌟🌟🌟')], default=None),
        ),
    ]
